spring:
  application:
    name: hotel-management-system

  datasource:
    url: jdbc:mysql://localhost:3306/Hotel_Managment
    username: root
    password: "root"
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

  data:
    redis:
      host: desirable-empirical-throne-30441.db.redis.io
      port: 10818
      username: default
      password: wKzSLBKC9VyUOCJq8Ty8qogHt0ZmERdr
#      ssl:
#        enabled: true

brevo:
  api:
    key: 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

  sender:
    email:  dalalstavan7@gmail.com
    name:  Hotel Aatithya

twilio:
  account-sid: AC758f931cd57c20ffd8412fcd24d0727c
  auth-token: a12825b464e118d2b1409e11c6b46442
  phone-number: +17372508034
