spring:
  application:
    name: hotel-management-system

  datasource:
    url: jdbc:mysql://localhost:3306/Hotel_Managment?createDatabaseIfNotExist=true
    username: root
    password: "vedant123"
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

app:
  security:
    admin-secret-key: "ADMIN@123"